---
title: "Assignment #6"
author: "YOUR FULL NAME"
format:
  html:
    toc: true
    number-sections: true
    embed-resources: true
---

# Assignment details  
In class, we interpolated the cleaned yield monitor data from a field in 2017.  

Now, you are asked to perform the same interpolation steps on the **cleaned** yield monitor data from the same field but collected in 2019 and 2020.  

The cleaned versions were created and exported during the previous assignment, likely saved in your project's `data` sub-folder.  If you can't find them, check your assignment #5 scripts, you will see there the path where you saved them and with what name.    

As part of the assignment, you will need to:  

- Interpolate each of the two data sets  
- Provide me with a statistical summary of the interpolated version to be included in the answers portion of this document (below).    
- Export the **interpolated vector version** to file (save it to the `data` folder of your personal project. Don't overwright any other files, follow a similar naming scheme as we did in class for the 2017 data).      

Some tips:  
- You can copy and paste the interpolation script twice, renaming each of the copies to something like `yield19_interpolation`.  

- Use each of the script copies to adapt for each of the new data sets.  

- You will need to adapt the file being read into R, and the name of the file being saved at the end. You may follow the same naming scheme as we did in class (just changing the year).   

- Deadline is Thursday Feb 22nd 11:59 pm (we will use all 3 interpolated cleaned yield data on our next steps). 

# Questions  

## What is the min, median, max for the **interpolated** cleaned yield data from 2019?  



## What is the min, median, max for the **interpolated** cleaned yield data from 2020?  
 

---

After answering all questions, include your last name on the file name (e.g., A6-questions-Bastos.qmd), render it, and send the .html to **lmbastos@uga.edu** by **Thursday, Feb 22nd 11:59 pm**.  
